### ISSUE TITLE
Function spaces and quadrature rules are created differently.

### ISSUE THREAD

**Issue by KristofferC** [KristofferC/JuAFEM.jl#61]
For example:

```jl
function_space = Lagrange{2, RefTetrahedron, 1}()
quad_rule = GaussQuadrature(Dim{2}, RefTetrahedron(), 1)
```

Better would probably be
```jl
function_space = Lagrange(Dim{2}, RefTetrahedron(), 1)
```

so they look the same.

Edit: It doesn't work because then we need like `Order{1}`...

**Comment by fredrikekre** [comment]
Change how the `quad_rule` is created instead?

```jl
quad_rule = GaussQuadrature{2, RefTetrahedron, 1}()
```

**Comment by KristofferC** [comment]
Problem is that a `QuadratureRule` is only parameterized by its dimension. The order and shape is just to help setup the points but after that they play no role.

**Comment by fredrikekre** [comment]
Okay,

wouldn't it make sense to parametrize `QuadratureRule` on (at least) the shape too?

And the order of the function space does not have the same meaning as the order you give to `QuadratureRule` so I don't think it is necessary that the `function_space` and `quad_rule` should be constructed in the same way.

**Comment by KristofferC** [comment]
I don't think it makes sense to parameterized on shape because a quadrature rule is simply a set of points in space with corresponding weights.

**Comment by fredrikekre** [comment]
which are distributed over a specific shape :p

Anyway, since the `quad_rule`'s `order` doesn't have the same meaning as the `function_space`'s `order` I don't feel its necessary the constructors are the same. It would have been another thing if all three parameters meant the same for both the `quad_rule` and the `function_space`. Then I would agree that it would be nice with the same way to construct them.

**Comment by fredrikekre** [comment]
I was actually thinking about this today, and don't we want to parametrize the `quad_rule` on the shape after all? That way we could create the `function_space` and `quad_rule` the same way and also parametrize the `FEValues` by the shape. That way we can stop usage of a` quad_rule` for a `RefTetrahedron` together with a function_space for a `RefCube`. Because right now you can do:

```jl
f_space = Lagrange{2, RefCube, 1}()
q_rule = QuadratureRule(Dim{1}, RefTetrahedron(), 2)
fe_v = FEValues(Float64, q_rule, f_space)
```
and it will work just fine.
